#!/usr/bin/perl

use feature 'say';  # say is a feature available since Perl v5.10, but it's not enabled without a use feature. or the statement below
#use v5.10;     #alternate


say "Hello World!";
